# Generated by Django 3.2.9 on 2021-11-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_interviewschedule_meeting_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewschedule',
            name='meeting_link',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
