# Generated by Django 3.2.9 on 2021-11-10 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_alter_interviewschedule_meeting_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewschedule',
            name='interviewee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='interview.interviewee'),
        ),
        migrations.AlterField(
            model_name='interviewschedule',
            name='interviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='interview.interviewer'),
        ),
    ]
